/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.abin.lee.thrift.enums;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OperateType implements TEnum {
  ADD(0),
  DELETE(1),
  UPDATE(3),
  FIND(4);

  private final int value;

  private OperateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperateType findByValue(int value) { 
    switch (value) {
      case 0:
        return ADD;
      case 1:
        return DELETE;
      case 3:
        return UPDATE;
      case 4:
        return FIND;
      default:
        return null;
    }
  }
}
